Enhanced Dockerfiles
microsoft/openjdk-docker pull request #14
Opened 2021-09-29 21:21 UTC by brunoborges

This PR addresses the following issues:

- No locale set by default
- Perform apt/yum upgrade
- Install ca-certificates, tzdata and font packages
- Perform a -Xshare:dump for faster startup time

2021-09-29 21:47 UTC, d3r3kk reviewed
Just a question about combining RUN commands to reduce docker image layers, but otherwise looks good.

2021-09-29 21:47 UTC, d3r3kk commented on docker/cbld/Dockerfile.msopenjdk-11-jdk
> +MAINTAINER Microsoft OpenJDK Support <openjdk-support@microsoft.com>
Nice one.

2021-09-29 21:47 UTC, d3r3kk commented on docker/cbld/Dockerfile.msopenjdk-11-jdk
> +RUN wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
Can we not run this sequence inside the previous RUN sequence? Cuts down on the number of layers IIRC to do it that way.

2021-09-29 21:47 UTC, d3r3kk commented on docker/ubuntu/Dockerfile.msopenjdk-17-jdk
> +    apt-get -qq autoremove --purge && \
Good catch.

2021-09-29 21:47 UTC, d3r3kk commented on docker/cbld/Dockerfile.msopenjdk-11-jdk
> +RUN wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
(This happens in a few other places as well in this change - can we collapse them all into one for each?)

2021-09-29 22:13 UTC, brunoborges commented on docker/cbld/Dockerfile.msopenjdk-11-jdk
> +RUN wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
Yes, it can.

2021-09-29 23:13 UTC, karianna requested changes
One Q about removing the cbl-d specific base image + I think the various sections could be commented a little e.g. Setting these vars to UTF-8 for consistent locale handling and so forth

2021-09-29 23:13 UTC, karianna commented on docker/cbld/Dockerfile.msopenjdk-11-jdk
> -    echo "deb https://packages.microsoft.com/repos/cbl-d quinault-universe main" >> /etc/apt/sources.list && \
Should we not retain this line?

2021-09-30 19:51 UTC, brunoborges commented on docker/cbld/Dockerfile.msopenjdk-11-jdk
> -    echo "deb https://packages.microsoft.com/repos/cbl-d quinault-universe main" >> /etc/apt/sources.list && \
Yes, this should've been kept!

2021-09-30 22:41 UTC, d3r3kk commented
Handle PR comments.

2021-09-30 23:14 UTC, karianna commented
note on the Dockerfiles: you can actually remove the -Xshare:dump present in the JDK 17 ones.

If we think the layers are self-explanatory then that's the last fix we need.  Else would be good to add some comments in the config explaining what some of it does

2021-10-01 17:50 UTC, d3r3kk commented
> note on the Dockerfiles: you can actually remove the -Xshare:dump present in the JDK 17 ones.
> 
> If we think the layers are self-explanatory then that's the last fix we need. Else would be good to add some comments in the config explaining what some of it does

I've removed the extra RUN statement altogether - this was to test that the java installation was working but it unnecessarily increases the container image size by ~5Mb (not much, but also has limited utility). We can move that test into a GH action instead - I have some scripts I can submit shortly that will do the trick.

2021-10-01 17:57 UTC, karianna approved these changes

2021-10-02 07:01 UTC, merged

2021-10-04 06:24 UTC, brunoborges commented
@d3r3kk @karianna the Xshare:dump was not intended to test, but to generate meta files for faster startup time.

The extra 5mb were exactly due to such file generation. This file exists by default with JDK 17.

I'll submit a new PR to add this back.