Add-non-root-test
microsoft/openjdk-docker pull request #60
Opened 2022-12-05 03:20 UTC by brunoborges

2022-12-05 03:26 UTC, karianna requested changes
GH Actions failing on validate phase.

2022-12-05 03:26 UTC, karianna commented on docker/test-only/NonRootUser.java
> +public class NonRootUser {
I would like my Javadoc and some sane whitespace please :-)

2022-12-05 03:26 UTC, karianna commented on docker/test-only/NonRootUser.java
> +  assert user != null : "user.name is null";
I get it's likely not worth adding a Testing lib for this, but perhaps consider for future tests?  Logging also.

2022-12-05 03:31 UTC, brunoborges commented on docker/test-only/NonRootUser.java
> +  assert user != null : "user.name is null";
Not sure. The goal is not to test the Java application, but the container image.

2022-12-05 03:32 UTC, brunoborges commented on docker/test-only/NonRootUser.java
> +public class NonRootUser {
Yeah yeah... VS Code is not formatting adequately at the moment. :/

2022-12-05 05:04 UTC, brunoborges commented on docker/test-only/NonRootUser.java
> +public class NonRootUser {
Formatting is fixed. :)

2022-12-06 21:25 UTC, karianna approved these changes
LGTM

2022-12-06 21:26 UTC, merged